### PR TITLE
Patch conditional compilation

### PR DESCRIPTION
**Pull request by arekbulski**
Most important change: in project settings, a flag similiar to DEBUG and TRACE gets computed for IsLittleEndian. The code actually compiles conditionally on it. Better performance. 

Someone needs to run test suite on it, I dont have it set up.

### CODE REVIEW

**Comment by LogicAndTrick** [comment]
A few questions:

- What happens if the user pulls in the pre-compiled DLL as a Nuget package if their architecture differs from the build machine?
- What happens if the user adds the uncompiled .cs files to their own project and they don't have the `LITTLEENDIAN` flag set up on their project?

**Comment by arekbulski** [comment]
- I have no idea how NuGet works. Impossible for me to say.
- That would cause a bug. I will fix the code so it detects this situation.

**Comment by GreyCat** [comment]
That's probably not a matter of how NuGet works, but how .NET assemblies work. As far as I understand, .NET assemblies are essentially CPU-neutral (setting compiler target for x64, x86 or arm doesn't seem to affect anything?), and CIL-to-machine code compilation is done during installation / loading of the DLL. Thus probably we can't do that in compile time.

**Comment by arekbulski** [comment]
We can adjust the code so that it has 3 branches, little big and default (current code). NuGet would use default but the user could take advantage of this feature if he adjusts his .csproj.

**Comment by GreyCat** [comment]
I have very vague idea of how .NET assemblies work, so it is really up to you guys to decide. If I'm right about the fact that they are essentially architecture-indepedent, then I'd vote to stick with current run-time detection routines, and, indeed, put alternative versions in the branches.

**Comment by arekbulski** [comment]
I have a very vague idea how assemblies compile as well, but as far as I understand it, even platform-independant code does not keep multiple versions per compile symbols. Ergo, it prunes the code during (pre)compilation. 

I will fix it.

**Review by Arlorean — COMMENTED** [review]
Instead of conditional compilation if we cache the bool locally on the KaitaiStream class:

`static readonly bool IsLittleEndian = BitConverter.IsLittleEndian;
`

Then use that in `ReadBytesNormalisedLittle/BigEndian` then the JIT compiler optimizes the Array.Reverse out when it doesn't apply. That way we get one nuget dll but optimal performance on all platforms.
Here is `ReadBytesNormalisedLittleEndian()`  on my machine, no `if` check or `Array.Reverse()`:
```
           byte[] bytes = ReadBytes(count);
038A0F50  mov         eax,edx  
038A0F52  sar         eax,1Fh  
038A0F55  push        eax  
038A0F56  push        edx  
038A0F57  call        038A0D90 
038A0F5C  ret 

```

**Comment by arekbulski** [comment]
Good find! +1

**Comment by arekbulski** [comment]
@Arlorean 
Could you check last commit and confirm its RTM, please?

**Review by Arlorean — APPROVED** [review]
This looks perfect!

**Pull request merged**
