### PR TITLE
Added ReadBitsIntLe method for algorithm specified @ issue#155

### PR DESCRIPTION
**Pull request by bibekdw**
ReadBitsIntLe method has been added to KataiStream.cs.

Attached one file to test with ksy and expected values.

regards,
[test_file.zip](https://github.com/kaitai-io/kaitai_struct_csharp_runtime/files/1985598/test_file.zip)

### CODE REVIEW

**Comment by indrora** [comment]
Does this match the behavior of other implementations?

**Comment by bibekdw** [comment]
I have no idea. This is implemented based on algorithm specified on issue# 155. It is working beautifully for my use case though.

**Comment by indrora** [comment]
The logic here matches what's in the Python and C++ versions. Any second opinions?

**Comment by GreyCat** [comment]
There is no "other implementations" yet in any of the runtimes to match this against. There is a Ruby implementation in https://github.com/kaitai-io/kaitai_struct/issues/155#issuecomment-331413570, but it's not even committed yet. Also, there is no ksc code that yields calls to `read_bits_int_le` yet too.

I guess we should start with something here, and C# might just work, so why not.

**Comment by indrora** [comment]
@graycat I see. The structure at least matches that seen in other `readBitsInt` implementations.

**Comment by GreyCat** [comment]
Thanks!

**Comment by kbreezy04** [comment]
Is there a way to use this code right now, I just ran into this exact problem with bit ints needing read as le

**Comment by bibekdw** [comment]
It is possible if you dont mind doing some manual work. You can actually just generate the c# class and change the method calls to ReadBitsInt to this new ReadBitsIntLe method.

**Comment by kbreezy04** [comment]
@bibekdw So far I've only used the web IDE and written ksy files.  I've got no problem getting into some deeper methods of use.  Can I compile this c# class and use the bX pattern with a ksy or is there a more advanced technique I'm going to have to implement....side note I'm asking questions on a commit so feel free to tell me to shut it.

**Comment by bibekdw** [comment]
You can use bX pattern with a ksy but the generated c# class will be calling to ReadBitsInt on KaitaiStream. You need to replace that with newly added ReadBitsIntLe.

**Pull request merged**
